### ISSUE TITLE
8266 uart_swap

### ISSUE THREAD

**Issue by rorso** [j0ta29/esphome#11]
Thank you for your code adaption. I tried as you suggested with the following configuration.

```
esphome:
  name: esphome-web-fcaf73
  friendly_name: esphome-web-fcaf73

esp8266:
  board: esp_wroom_02

# Enable logging
logger:
  hardware_uart: UART1
  baud_rate: 0
  level: DEBUG


# Enable Home Assistant API
api:
  encryption:
    key: "-----------------------------------"

ota:
  password: "fe027c2092664e42861b2890f8788a2f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Fcaf73"
    password: "--------------------"

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/j0ta29/esphome
      ref: uart_swap
    components: [ optolink ]

optolink:
  protocol: P300
  tx_pin: GPIO15
  rx_pin: GPIO13
  logger: enable             # wenn später alles rund läuft, wieder entfernen 

text_sensor:
  - platform: optolink
    name: device_info
    mode: DEVICE_INFO

  - platform: optolink
    name: state
    mode: STATE_INFO
```
I was allowed to configure the alternate GPIO pins - and just these. Others are rejected.

But the running code still sends on the `tx` and not on the `GPIO15` pin.
