### ISSUE TITLE
Home Asistant API connection constantly connects and drops when using text_sensors

### ISSUE THREAD

**Issue by j0ta29** [j0ta29/esphome#20]
Reported by @jvthienen:

There seems to be issues when reading text_sensors. If I enable these, the ESP32 starts and runs on it's own and does not restart, but the Home Asistant API connection constantly connects and drops.

```
# Example sensor, but it's pretty much with most text_sensors
text_sensor:
  - platform: optolink
    # Unit: DT // Length: 4
    name: "Boiler KS Card Type"
    id: boiler_ks_card_type
    entity_category: "diagnostic"
    address: 0x7656
    bytes: 4
    type: RAW
    update_interval: 123s
```

**Comment by darth-hp** [comment]
I have seen this only with `type: RAW` - below types work:

``` yaml
text_sensor:
  - platform: optolink
    type: DEVICE_INFO
    name: Device Info
    update_interval: 60s
  - platform: optolink
    type: STATE_INFO
    name: Component state
    update_interval: 15s
  - platform: optolink
    name: Betriebsart (aktuell)
    address: 0x2301
    bytes: 1
    icon: mdi:water-boiler
    type: MAP
    filters:
      map:
        - "0 -> Sommerbetrieb"
        - "1 -> Dauernd Reduziert"
        - "2 -> Dauernd Normal"
        - "3 -> Heizen + Warmwasser"
        - "4 -> Normal Ausgeschaltet"
        - "5 -> Dauernd Ausgeschaltet"
    update_interval: 60s
```
