### ISSUE TITLE
support for esp-idf framework

### ISSUE THREAD

**Issue by snailcatcher** [j0ta29/esphome#23]
Will it be possible to support the esp-idf framework in the future?

e.g.
```
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 4MB
  variant: ESP32S3
  framework:
    type: esp-idf
```
Sincerly snailcatcher
