### ISSUE TITLE
Gas boiler start is blocked while ESP is connected

### ISSUE THREAD

**Issue by SuperMasterPhoenix** [j0ta29/esphome#6]
As already mentioned in the Pull Request comments (e.g. https://github.com/esphome/esphome/pull/4453#issuecomment-1826263264) the gas boiler does not start in case an active ESP device is connected to it during that time. It seems that the continous requests are somehow interfering with the boot process.

I'm not sure whether this issue should be handled by your code or within the underlying VitoWIFI lib, but I just wanted to add here for completeness :-)

**Comment by j0ta29** [comment]
Current version (2024-07-24) detects communication problems (for instance while boiler is switched of) and pauses communication for 10 seconds.
`STATE_INFO` `text_sensor` shows communication state:

```
text_sensor:
  - platform: optolink
    type: STATE_INFO
    name: Optolink state info
    update_interval: 1s
```
